### ISSUE TITLE
Issues in running build.sh

### ISSUE THREAD

**Issue by ShijiMariam** [mmastrac/oblivious-cpu#1]
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-readable POM /home/shiji/oblivious-cpu/bin/parent/pom.xml: /home/shiji/oblivious-cpu/bin/parent/pom.xml (No such file or directory) @ 
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project  (/home/shiji/oblivious-cpu/bin/parent/pom.xml) has 1 error
[ERROR]     Non-readable POM /home/shiji/oblivious-cpu/bin/parent/pom.xml: /home/shiji/oblivious-cpu/bin/parent/pom.xml (No such file or directory)
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

**Comment by mmastrac** [comment]
Are you running `bin/build.sh` from inside the `oblivious-cpu` directory?

**Comment by ShijiMariam** [comment]
yes

**Comment by mmastrac** [comment]
Can you start fresh and show me the terminal commands you used?

It seems to work for me:

```
matts-mbp:tmp matt$ git clone --recursive https://github.com/mmastrac/oblivious-cpu.git
Cloning into 'oblivious-cpu'...
remote: Counting objects: 1141, done.
remote: Total 1141 (delta 0), reused 0 (delta 0), pack-reused 1141
Receiving objects: 100% (1141/1141), 151.58 KiB | 153.00 KiB/s, done.
Resolving deltas: 100% (388/388), done.
Submodule 'docopt' (https://github.com/docopt/docopt.java.git) registered for path 'docopt'
Cloning into '/private/tmp/oblivious-cpu/docopt'...
Submodule path 'docopt': checked out 'c3f65a503de43b6a30e928db4166b469724c7a60'
matts-mbp:tmp matt$ cd oblivious-cpu/
matts-mbp:oblivious-cpu matt$ bin/build.sh
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.grack.obliviouscpu:core:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ com.grack.obliviouscpu:core:[unknown-version], /private/tmp/oblivious-cpu/core/pom.xml, line 23, column 12
```

**Comment by ShijiMariam** [comment]
It works fine now. Thanks

**Comment by mmastrac** [comment]
OK, closing this issue for now.
